spring:
  application:
    name: Mybatis-plus samples
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-plus-sample?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    initialization-mode: always
#    schema:
#      - classpath:init-sql/init.sql
    druid:
      filters: wall,stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.css,*.jpg,*.gif,*.bmp,*.ico,*.png
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: session_name
        principal-cookie-name: cookie_name
      stat-view-servlet:
        enable: true
        reset-enable: false
        login-username: admin
        login-password: 123
mybatis:
  type-aliases-package: com.tz.mybatis.sample.entity
  mapper-default-scope: com.tz.mybatis.sample.mapper
  mapper-locations: classpath:mappers/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      # 逻辑删除字段
      logic-delete-field: deleted
      # 逻辑删除值 1
      logic-delete-value: 1
      # 未逻辑删除值 0
      logic-not-delete-value: 0
logging:
  level:
    com.tz.mybatis.sample.mapper: debug